name: ArenaBlutonium
main: mc.adambor.ab.Main
version: 0.1.2
author: adambor
depend: [BattleArena]
description: Version 0 of ArenaBlutonium
commands:
  ab:
    description: Arena Blutonium
    aliases: [ab]
    usage: /ab <addBlutonium|clearBlutonium|addCompressors|clearCompressors|setScoreToWin>
